apiVersion: skaffold/v2beta15
kind: Config
build:
    local:
        push: false
    artifacts:
        -   image: frontend-fastapi
            context: frontend
            docker:
                dockerfile: Dockerfile.dev
            sync:
                manual:
                # Sync all the javascript files that are in the src folder
                # with the container src folder
                -   src: 'src/**/*.tsx'
                    dest: .
                -   src: 'src/**/*.ts'
                    dest: .
                -   src: 'src/**/*.js'
                    dest: .
                -   src: 'src/**/*.jsx'
                    dest: .
                -   src: 'src/**/*.html'
                    dest: .
                -   src: 'src/**/*.css'
                    dest: .
        -   image: backend-fastapi
            context: backend
            sync:
                infer:
                    - '**/*.py'
            docker:
                dockerfile: Dockerfile
    # tagPolicy:
    #     gitCommit: {}
deploy:
    kubectl:
        manifests:
            -   k8s/*
